// Every LinkSnap feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 52 feature routes of the LinkSnap API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** A file upload's body: a FormData with each file (a Blob; a File keeps its name) and
   *  the other fields as text. The client's apigenRequest sends a FormData as it is. */
  private form(fields: Record<string, unknown>): FormData {
    const form = new FormData();
    for (const [k, v] of Object.entries(fields)) {
      if (v === undefined || v === null) continue;
      form.append(k, v instanceof Blob ? v : typeof v === 'string' ? v : JSON.stringify(v));
    }
    return form;
  }

  /** List audit log (GET /api/v1/audit-log) */
  auditLogList(input?: { "action"?: unknown; "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["action"] = all["action"]; delete all["action"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/audit-log`, query, undefined);
  }

  /** Cancel the active paid subscription at period end. (POST /api/v1/billing/cancel) */
  billingCancel(): Promise<unknown> {
    return this.call("POST", `/api/v1/billing/cancel`, {}, undefined);
  }

  /** Create a Plugipay checkout session for the selected LinkSnap tier. (POST /api/v1/billing/checkout) */
  billingCheckout(input?: { "currency"?: unknown; "plan"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** /billing/webhook/storlaunch was the legacy receiver back when LinkSnap routed checkout through Storlaunch's Midtrans wrapper. (POST /api/v1/billing/downgrade) */
  billingDowngrade(input?: { "plan"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/downgrade`, query, all);
  }

  /** Billing history (paginated) (GET /api/v1/billing/history) */
  billingHistory(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/billing/history`, query, undefined);
  }

  /** Alias for history (GET /api/v1/billing/invoices) */
  billingInvoices(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/billing/invoices`, query, undefined);
  }

  /** Return current user's plan with all limits (GET /api/v1/billing/plan) */
  billingPlan(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plan`, {}, undefined);
  }

  /** Return all 3 plans with IDR prices (public, no auth needed) (GET /api/v1/billing/plans) */
  billingPlans(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plans`, {}, undefined);
  }

  /** Return current subscription details (GET /api/v1/billing/subscription) */
  billingSubscription(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/subscription`, {}, undefined);
  }

  /** Return current usage vs plan limits (GET /api/v1/billing/usage) */
  billingUsage(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/usage`, {}, undefined);
  }

  /** Add custom domain (POST /api/v1/domains) */
  domainsCreate(input?: { "domain"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/domains`, query, all);
  }

  /** Remove domain (DELETE /api/v1/domains/{id}) */
  domainsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/domains/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get single domain (GET /api/v1/domains/{id}) */
  domainsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/domains/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List custom domains (GET /api/v1/domains) */
  domainsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/domains`, {}, undefined);
  }

  /** Verify domain DNS (POST /api/v1/domains/{id}/verify) */
  domainsVerify(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/domains/${encodeURIComponent(id)}/verify`, {}, undefined);
  }

  /** Bulk operations (POST /api/v1/links/bulk) */
  linksBulk(input?: { "action"?: unknown; "ids"?: unknown; "tag"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/links/bulk`, query, all);
  }

  /** Create link (POST /api/v1/links) */
  linksCreate(input?: { "expiresAt"?: unknown; "maxClicks"?: unknown; "slug"?: unknown; "tags"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/links`, query, all);
  }

  /** Delete link (DELETE /api/v1/links/{id}) */
  linksDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/links/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Export links - MUST be before /:id to avoid matching 'export' as an ID (GET /api/v1/links/export) */
  linksExport(input?: { "format"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["format"] = all["format"]; delete all["format"];
    return this.call("GET", `/api/v1/links/export`, query, undefined);
  }

  /** Get link by ID or slug (GET /api/v1/links/{id}) */
  linksGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/links/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Import links (JSON body) (POST /api/v1/links/import) */
  linksImport(input?: { "dryRun"?: unknown; "links"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/links/import`, query, all);
  }

  /** List links (GET /api/v1/links) */
  linksList(input?: { "cursor"?: unknown; "limit"?: unknown; "order"?: unknown; "q"?: unknown; "sort"?: unknown; "status"?: unknown; "tag"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["order"] = all["order"]; delete all["order"];
    query["q"] = all["q"]; delete all["q"];
    query["sort"] = all["sort"]; delete all["sort"];
    query["status"] = all["status"]; delete all["status"];
    query["tag"] = all["tag"]; delete all["tag"];
    return this.call("GET", `/api/v1/links`, query, undefined);
  }

  /** List stats (GET /api/v1/links/{id}/stats) */
  linksStats(id: string, input?: { "from"?: unknown; "to"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["from"] = all["from"]; delete all["from"];
    query["to"] = all["to"]; delete all["to"];
    return this.call("GET", `/api/v1/links/${encodeURIComponent(id)}/stats`, query, undefined);
  }

  /** Get link stats (GET /api/v1/links/{id}/stats/export) */
  linksStatsExport(id: string, input?: { "format"?: unknown; "from"?: unknown; "to"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["format"] = all["format"]; delete all["format"];
    query["from"] = all["from"]; delete all["from"];
    query["to"] = all["to"]; delete all["to"];
    return this.call("GET", `/api/v1/links/${encodeURIComponent(id)}/stats/export`, query, undefined);
  }

  /** Update link (PATCH /api/v1/links/{id}) */
  linksUpdate(id: string, input?: { "expiresAt"?: unknown; "maxClicks"?: unknown; "slug"?: unknown; "status"?: unknown; "tags"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/links/${encodeURIComponent(id)}`, query, all);
  }

  /** Create QR code (POST /api/v1/qr-codes) */
  qrCodesCreate(input?: { "expiresAt"?: unknown; "linkId"?: unknown; "logoRunRef"?: unknown; "maxScans"?: unknown; "styleConfig"?: unknown; "tags"?: unknown; "title"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/qr-codes`, query, all);
  }

  /** Delete QR code (DELETE /api/v1/qr-codes/{id}) */
  qrCodesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/qr-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Download QR code image — MUST be before /:id Supports both Authorization header and ?token= query parameter (GET /api/v1/qr-codes/{id}/download) */
  qrCodesDownload(id: string, input?: { "format"?: unknown; "token"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["format"] = all["format"]; delete all["format"];
    query["token"] = all["token"]; delete all["token"];
    return this.call("GET", `/api/v1/qr-codes/${encodeURIComponent(id)}/download`, query, undefined);
  }

  /** Generate download token — MUST be before /:id (POST /api/v1/qr-codes/{id}/download-token) */
  qrCodesDownloadToken(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/qr-codes/${encodeURIComponent(id)}/download-token`, {}, undefined);
  }

  /** Get single QR code (GET /api/v1/qr-codes/{id}) */
  qrCodesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/qr-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List QR codes (GET /api/v1/qr-codes) */
  qrCodesList(input?: { "cursor"?: unknown; "limit"?: unknown; "linkId"?: unknown; "q"?: unknown; "status"?: unknown; "tag"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["linkId"] = all["linkId"]; delete all["linkId"];
    query["q"] = all["q"]; delete all["q"];
    query["status"] = all["status"]; delete all["status"];
    query["tag"] = all["tag"]; delete all["tag"];
    return this.call("GET", `/api/v1/qr-codes`, query, undefined);
  }

  /** Get QR code stats — MUST be before /:id (GET /api/v1/qr-codes/{id}/stats) */
  qrCodesStats(id: string, input?: { "from"?: unknown; "to"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["from"] = all["from"]; delete all["from"];
    query["to"] = all["to"]; delete all["to"];
    return this.call("GET", `/api/v1/qr-codes/${encodeURIComponent(id)}/stats`, query, undefined);
  }

  /** Update QR code (PATCH /api/v1/qr-codes/{id}) */
  qrCodesUpdate(id: string, input?: { "expiresAt"?: unknown; "logoRunRef"?: unknown; "maxScans"?: unknown; "status"?: unknown; "styleConfig"?: unknown; "tags"?: unknown; "title"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/qr-codes/${encodeURIComponent(id)}`, query, all);
  }

  /** Upload a logo for the QR code's center (on plans with qrLogoEnabled — every plan today) (POST /api/v1/qr-codes/upload-logo) */
  qrCodesUploadLogo(input: { "logo": Blob }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/qr-codes/upload-logo`, query, this.form(all));
  }

  /** Create tag (POST /api/v1/tags) */
  tagsCreate(input?: { "name"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/tags`, query, all);
  }

  /** Detaches it from every link and QR code. (DELETE /api/v1/tags/{id}) */
  tagsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/tags/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List tags (GET /api/v1/tags) */
  tagsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/tags`, {}, undefined);
  }

  /** Rename tag — the tag keeps its id, so every link and QR code that carries it follows the rename for free (implicit m2m join rows key on the id, not the name). (PATCH /api/v1/tags/{id}) */
  tagsUpdate(id: string, input?: { "name"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/tags/${encodeURIComponent(id)}`, query, all);
  }

  /** Create endpoint — returns the whsec_ secret once. (POST /api/v1/webhooks) */
  webhooksCreate(input?: { "events"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhooks`, query, all);
  }

  /** Remove endpoint. (DELETE /api/v1/webhooks/{id}) */
  webhooksDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhooks/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List endpoints (never includes the secret). (GET /api/v1/webhooks) */
  webhooksList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks`, {}, undefined);
  }

  /** Pause / resume delivery, or edit the endpoint's url / events. (PATCH /api/v1/webhooks/{id}) */
  webhooksUpdate(id: string, input?: { "active"?: unknown; "events"?: unknown; "url"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhooks/${encodeURIComponent(id)}`, query, all);
  }

  /** Create new workspace (POST /api/v1/workspaces) */
  workspacesCreate(input?: { "name"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/workspaces`, query, all);
  }

  /** Invite member (POST /api/v1/workspaces/current/members) */
  workspacesCreateCurrentMembers(input?: { "email"?: unknown; "role"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/workspaces/current/members`, query, all);
  }

  /** Get active workspace details (GET /api/v1/workspaces/current) */
  workspacesCurrent(): Promise<unknown> {
    return this.call("GET", `/api/v1/workspaces/current`, {}, undefined);
  }

  /** List members (GET /api/v1/workspaces/current/members) */
  workspacesCurrentMembers(): Promise<unknown> {
    return this.call("GET", `/api/v1/workspaces/current/members`, {}, undefined);
  }

  /** Workspace stats (GET /api/v1/workspaces/current/stats) */
  workspacesCurrentStats(input?: { "from"?: unknown; "to"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["from"] = all["from"]; delete all["from"];
    query["to"] = all["to"]; delete all["to"];
    return this.call("GET", `/api/v1/workspaces/current/stats`, query, undefined);
  }

  /** Remove member (DELETE /api/v1/workspaces/current/members/{id}) */
  workspacesDeleteCurrentMembers(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/workspaces/current/members/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Huudis is the source of truth. (GET /api/v1/workspaces) */
  workspacesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/workspaces`, {}, undefined);
  }

  /** Switch active workspace (POST /api/v1/workspaces/switch) */
  workspacesSwitch(input?: { "workspaceId"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/workspaces/switch`, query, all);
  }

  /** Update active workspace (PATCH /api/v1/workspaces/current) */
  workspacesUpdateCurrent(input?: { "name"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/workspaces/current`, query, all);
  }

  /** Change a member's role. (PATCH /api/v1/workspaces/current/members/{id}) */
  workspacesUpdateCurrentMembers(id: string, input?: { "role"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/workspaces/current/members/${encodeURIComponent(id)}`, query, all);
  }
}
